services:
  app:
    image: harbor.signmax.cloud/public/devcontainer:rails-3.4.5-14
    volumes:
      - ..:/workspaces/remixbase:cached
    shm_size: "1gb"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
